# Generated by Django 3.2.7 on 2022-02-18 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('story', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 2, 18, 11, 27, 57, 900209, tzinfo=utc))),
            ],
        ),
    ]
