# Generated by Django 3.2.7 on 2022-02-18 12:23

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='liked_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=[0], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 2, 18)),
        ),
    ]
