# Generated by Django 3.2.7 on 2022-02-19 07:54

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20220218_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 2, 19)),
        ),
        migrations.AlterField(
            model_name='content',
            name='liked_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=None),
        ),
    ]
