# Generated by Django 3.2.7 on 2022-02-19 08:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20220219_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='liked_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None),
        ),
    ]
