# Generated by Django 3.2.7 on 2022-02-19 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='liked_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=[0], size=None),
        ),
    ]
